name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Check Current Directory
        run: pwd

      - name: List Files
        run: ls -al

      - name: Build with Maven
        run: |
          mvn clean package  # No need to change directories
      - name: Run tests
        run: |
          mvn test  # No need to change directories
