name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and test
        run: |
          mvn clean package
      - name: Generate report
        run: |
          mvn site
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: target/site
